repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-toml
      - id: check-json
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: sort-simple-yaml
        files: keywords\.yaml$
