repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-toml
      - id: check-json
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: sort-simple-yaml
        files: keywords\.yaml$

  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
        additional_dependencies:
          - toml

  - repo: https://github.com/psf/black
    rev: 21.4b2
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
