dist: xenial
language: python
git:
  # Clone the full depth for setuptools_scm (to count commits in very large
  # branches)
  depth: false
matrix:
  include:
    - python: "3.7"
install:
  - pip install .[dev]
script:
  pytest
